spring:
  application:
    name: drug-prevention-system

  datasource:
    url: jdbc:mysql://localhost:3306/drug_prevention_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true
    username: root
    password: đệ̉̀̃ộêâ
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  security:
    oauth2:
      resourceserver:
        jwt:
          secret-key: drugPreventionSecretKeyForJWTTokenGeneration2024

  mail:
    host: smtp.gmail.com
    port: 587
    username: ${MAIL_USERNAME:}
    password: ${MAIL_PASSWORD:}
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8080
  servlet:
    context-path: /api

logging:
  level:
    com.drugprevention: DEBUG
    org.springframework.security: DEBUG

app:
  jwt:
    secret: drugPreventionSecretKeyForJWTTokenGeneration2024
    expiration: 86400000 # 24 hours

  cors:
    allowed-origins:
      - http://localhost:3000
      - http://localhost:5173
      - http://localhost:8080

management:
  endpoints:
    web:
      exposure:
        include: health,info,metrics

---
# H2 Database Profile for quick testing
spring:
  config:
    activate:
      on-profile: h2
  datasource:
    url: jdbc:h2:mem:drugprevention
    driver-class-name: org.h2.Driver
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: true
